#!/bin/bash
#
# Mingi jura script
#
echo -n "Tere
" # väljasta eestikeelne tervitus
echo -n "Hello
" # väljasta inglisekeelne tervitus
echo -n "Hallo
" #väljasta saksakeelne tervitus
#
# skripti lõpp
